<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSdkjxx2\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSdkjxx2/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerSdkjxx2.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerSdkjxx2\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerSdkjxx2\appProdProjectContainer([
    'container.build_hash' => 'Sdkjxx2',
    'container.build_id' => '1a1ce8c7',
    'container.build_time' => 1666719527,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSdkjxx2');
