<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAv2bck7\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAv2bck7/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerAv2bck7.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerAv2bck7\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerAv2bck7\appProdProjectContainer([
    'container.build_hash' => 'Av2bck7',
    'container.build_id' => '655e63de',
    'container.build_time' => 1670323251,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAv2bck7');
