version: '3.17'

services:
  be_184542_presta:
    image: mojapresta
    environment: 
      - DATABASE_HOST=be_184542_db
      - DATABASE_PORT=3306
      - DATABASE_NAME=prestashop
      - DATABASE_USER=prestashopuser
      - DATABASE_PASSWORD=test
    ports: 
      - 18456:80
      - 18455:443
  be_184542_db: 
    image: mojamaria
    environment: 
      - MARIADB_ROOT_PASSWORD=test
      - MARIADB_USER=prestashopuser
      - MARIADB_PASSWORD=test
      - MARIADB_DATABASE=prestashop
    ports:
      - 18457:3306
