services:
  ps_metrics.provider.analyticsaccountslist:
    class: 'PrestaShop\Module\Ps_metrics\Provider\AnalyticsAccountsListProvider'
    public: true
    arguments:
      - "@ps_metrics.repository.configuration"
      - "@ps_metrics.api.analytics"

  ps_metrics.provider.googletag:
    class: 'PrestaShop\Module\Ps_metrics\Provider\GoogleTagProvider'
    public: true
    arguments:
      - "@ps_metrics.api.http"
